---
- hosts: all
  tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago (apt update)
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to the latest version (apt upgrade)
      apt:
        name: "*"
        state: latest
        force_apt_get: true

    - name: Update all packages to the latest version (apt dist-upgrade)
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache (apt autoclean)
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required (apt autoremove)
      apt: autoremove=yes
